// content.js — all chapter content (the CH array). Edit explanations here.
var CH=[

// ---------- ESSENTIALS ----------
{sec:"Essentials",title:"Starting a repo",diff:1,show:{},selfContained:true,
 blurb:"Every project that uses git is a “repository” — a folder git keeps an eye on. There are two ways to get one: start a fresh repo, or copy an existing one.",
 onEnter:function(){S=blank();S.local={};S.inited=false;fb=null},
 missions:[
  {t:"Turn this folder into a repo",
   lay:"git init turns the plain folder you're in into something git watches. You run it once, right at the start of a project — after that, git can save snapshots of your work whenever you ask.",
   tech:"Technically it creates a hidden “.git” sub-folder inside the current directory. That folder is where git stores every commit, branch and scrap of history; your own files are left exactly as they were.",
   syntax:[{t:"git init",k:"cmd",note:"in everyday use you run it with no arguments — it just acts on the folder you're in (it can take an optional directory or flags like -b, but you rarely need them)"}],
   goal:"Initialise a git repository in this folder.",
   chk:function(c){return /^git\s+init/.test(c.trim())}},
  {t:"Check the status",
   lay:"git status is the question you'll ask git most often: “where are we?” It tells you what has changed and what's ready to be saved, and it never changes anything itself — so it's always safe to run.",
   tech:"It reports the branch you're on plus the state of your files across the working directory and the staging area. On a brand-new repo it simply says “No commits yet.”",
   syntax:[{t:"git status",k:"cmd",note:"takes no arguments"}],
   goal:"Check the status of your new, empty repository.",
   setup:function(){S.local={main:[]};S.inited=true},
   chk:function(c){return /^git\s+status/.test(c.trim())}},
  {t:"Or: copy an existing project",
   lay:"git clone makes your own copy of a project that already lives somewhere else — usually on GitHub. You use init to start a project from scratch, and clone to join one that already exists.",
   tech:"It downloads every file and the project's complete history into a new folder, sets up a link back to the source (which git names “origin”), and checks out the default branch so you're ready to work. In effect: init + download everything + remember the source.",
   syntax:[{t:"git clone",k:"cmd"},{t:"<url>",k:"arg",note:"required — the repository's web address, e.g. https://github.com/anthropics/courses.git"},{t:"[<folder>]",k:"arg",note:"optional — a name for the new folder; defaults to the repo's own name"}],
   goal:"Clone the project at https://github.com/anthropics/courses.git onto your computer.",
   setup:function(){S.local={};S.inited=false},
   chk:function(c){return /^git\s+clone\s+\S/.test(c.trim())}}
 ],
 recap:"git init = start a repo from scratch · git status = “where are we?” · git clone <url> = copy a repo that already exists."},

{sec:"Essentials",title:"First commits",diff:1,show:{},selfContained:true,
 blurb:"A change moves through three places before it's saved for good: your working folder → the staging area → committed history. Let's push one change all the way through, then learn the shortcut.",
 onEnter:function(){S=blank();fb=null},
 missions:[
  {t:"Check the status",
   lay:"You've edited notes.txt. git status shows you that the change exists but hasn't been saved yet — it's sitting in your working folder, “not staged”.",
   tech:"git status groups changes by which of git's three areas they're in: the working directory (edits you've made), the staging area (changes lined up for the next commit), and committed history.",
   syntax:[{t:"git status",k:"cmd",note:"takes no arguments"}],
   goal:"Run a status check to see notes.txt waiting in your working folder.",
   setup:function(){seed('notes.txt')},chk:function(c){return /^git\s+status/.test(c.trim())}},
  {t:"Stage the change",
   lay:"Staging is you choosing what goes into the next snapshot. git add copies notes.txt into the staging area so it'll be included when you commit — nothing is permanently saved yet, you're just lining it up.",
   tech:"git add records the current contents of the files you name in the staging area (git's “index”). Common forms: a single file, “.” for everything in the current folder, “-A” for the whole repo, or “-p” to approve changes one chunk at a time.",
   syntax:[{t:"git add",k:"cmd"},{t:"<file>",k:"arg",note:"the path to stage — or “.” for everything in this folder, “-A” for the whole repo, “-p” to choose chunk by chunk"}],
   goal:"Stage notes.txt for the next commit.",
   setup:function(){seed('notes.txt')},chk:function(){return S.staging.length>0}},
  {t:"Commit it",
   lay:"A commit is a permanent, labelled snapshot of everything you've staged. git commit seals notes.txt into history with a short message, so future-you knows what changed.",
   tech:"git commit records whatever is in the staging area as a new commit. The -m flag attaches the message inline; leave it off and git opens a text editor for you to write one. Nothing reaches history until you commit.",
   syntax:[{t:"git commit",k:"cmd"},{t:"-m",k:"flag",note:"short for “message” — write the commit message right here instead of opening an editor"},{t:"\"<message>\"",k:"arg",note:"you replace this — a short description of the change, in quotes"}],
   goal:"Commit your staged change with the message “edit notes”.",
   setup:function(){seed('notes.txt');S.staging.push(S.working.pop())},chk:function(){return hl('main')>=2}},
  {t:"Do the whole loop again",cmd:"git add + commit",
   lay:"That edit → add → commit cycle is the heartbeat of git — you'll do it thousands of times. This time, do both steps yourself.",
   tech:"The shortcut git commit -am \"<msg>\" stages and commits in one move — but only for files git already tracks; brand-new files still need a plain git add first.",
   syntax:[{t:"git add",k:"cmd"},{t:".",k:"arg",note:"stage everything in the current folder"},{t:";",k:"sh",note:"a shell separator (not part of git) — runs the next command after this one; you could also just press Enter between the two commands"},{t:"git commit",k:"cmd"},{t:"-m",k:"flag"},{t:"\"<message>\"",k:"arg",note:"your message — or use git commit -am \"…\" to do add + commit in one step"}],
   goal:"Stage notes.txt and commit it (any message). You've now done the full loop on your own.",
   setup:function(){S.local={main:['c0','c1']};seed('notes.txt')},chk:function(){return hl('main')>=3}}
 ],
 recap:"add = pack the box (./-A/-p variants) · commit -m = seal + label it · commit -am = add + commit in one (tracked files only)."},

{sec:"Essentials",title:"Looking around",diff:1,show:{},selfContained:true,
 blurb:"Before you change anything, it helps to look. Two commands answer the questions you'll ask constantly: “what happened here?” (log) and “what did I just touch?” (diff). Neither one changes a thing — they're read-only, so you can run them as often as you like.",
 onEnter:function(){S=blank();S.local={main:['c0','c1','c2']};fb=null},
 missions:[
  {t:"Read the history",
   lay:"git log is your project's diary. It prints every commit you've made, newest first, so you can scroll back through the whole story of what changed and why. It only reads history — running it never alters anything.",
   tech:"git log walks backwards from where you're standing (HEAD), following each commit to its parent, and prints each one with its full id, author, date and message. The plain form is wordy on purpose; you'll soon reach for the tidier views.",
   syntax:[{t:"git log",k:"cmd",note:"with no arguments it lists every commit on the current branch, newest first; it takes many optional flags, but you rarely need them to start"}],
   goal:"Show the list of commits on this branch.",
   chk:function(c){return /^git\s+log/.test(c.trim())}},
  {t:"The compact view",
   lay:"git log --oneline is the same diary with the waffle trimmed off — one neat line per commit, just a short id and the message. This is the version most people actually live in day to day.",
   tech:"The --oneline flag collapses each commit to its abbreviated hash plus the first line of its message. Pair it with --graph later and git will draw your branches and merges as a little ASCII tree right in the terminal.",
   syntax:[{t:"git log",k:"cmd"},{t:"--oneline",k:"flag",note:"squashes each commit down to one tidy line — short id plus message — instead of the full multi-line entry"}],
   goal:"Show the same history, but one line per commit.",
   chk:function(c){return /^git\s+log\s+--oneline/.test(c.trim())}},
  {t:"See your unsaved changes",
   lay:"git diff is the “spot the difference” between the files on your desk right now and the last snapshot you committed. You've edited config.txt but haven't staged it yet — diff shows you exactly which lines you changed before you commit to anything.",
   tech:"With no arguments, git diff compares your working directory against the staging area, line by line: removed lines are marked with a minus, added lines with a plus. It deliberately shows only UNSTAGED changes — once a file is staged, plain diff goes quiet about it. A great habit is to run it right before git add.",
   syntax:[{t:"git diff",k:"cmd",note:"with no arguments it shows the changes in your working folder that you haven't staged yet"}],
   goal:"You've edited config.txt but not staged it. Show exactly what changed.",
   setup:function(){seed('config.txt')},
   chk:function(c){return /^git\s+diff(?!\s+--staged)/.test(c.trim())}},
  {t:"See what's about to be committed",cmd:"git add + git diff --staged",
   lay:"Here's the catch that trips up nearly everyone: the moment you git add a file, plain git diff shows nothing for it — because there's no longer a difference between your desk and the staging area. To peek at what's actually lined up for the next commit, you ask git diff --staged. It's your last look before you seal the box.",
   tech:"git diff --staged (also spelled --cached) compares the staging area against the last commit, rather than your working folder against the staging area. So you'll stage config.txt first, then diff the staged copy. Stringing two commands with a semicolon is a shell convenience, not a git feature — it just runs the second after the first.",
   syntax:[{t:"git add",k:"cmd"},{t:"config.txt",k:"arg",note:"the file to stage so there's something staged to inspect"},{t:";",k:"sh",note:"a shell separator (not part of git) — runs the next command after this one; you could also just press Enter between the two"},{t:"git diff",k:"cmd"},{t:"--staged",k:"flag",note:"shows the changes that are staged and about to be committed, comparing the staging area to the last commit (--cached means the same thing)"}],
   goal:"Stage config.txt, then diff the staged version to see what's about to be committed.",
   setup:function(){seed('config.txt')},
   chk:function(c){return S.staging.indexOf('config.txt')>-1&&/^git\s+diff\s+--staged|^git\s+diff\s+--cached/.test(c.trim())}}
 ],
 recap:"log = the diary (--oneline / --graph to tidy it) · diff = unsaved changes on your desk · diff --staged = what's in the box, about to be committed."},

{sec:"Essentials",title:"Branches & switching",diff:2,show:{branches:true,graph:true},selfContained:true,
 blurb:"A branch is a parallel universe for your code — a place to try things without touching the main timeline. You'll make one, work on it, hop between them, and clean up after. The graph below draws each branch as its own line.",
 onEnter:function(){S=blank();S.local={main:['c0','c1']};fb=null},
 missions:[
  {t:"List your branches",
   lay:"git branch on its own is just a roll-call: it lists every branch you have and puts a little star next to the one you're standing on. It changes nothing — it's the “who's here?” command. Right now there's only main, and that's where you are.",
   tech:"With no arguments, git branch prints your local branches and marks the current one (the branch HEAD points at) with an asterisk. HEAD is git's name for “you are here” — the branch your next commit will attach to. Give it a name instead and it CREATES that branch (without moving onto it); add -d or -D to delete one.",
   syntax:[{t:"git branch",k:"cmd",note:"with no arguments it just lists your branches and stars the current one — it doesn't switch or change anything"}],
   goal:"List the branches that exist right now.",
   chk:function(c){return /^git\s+branch\s*$/.test(c.trim())}},
  {t:"Create a branch and hop onto it",
   lay:"git switch -c feature means “create a new branch called feature and step onto it in one move.” Think of a branch as a sticky note pointing at your current commit — making one is instant and basically free, so branch early and often. From here, anything you do happens on feature and leaves main alone.",
   tech:"The -c flag tells switch to create the branch before moving to it. The new branch starts at your current commit and HEAD is repointed to it, so commits now land there. You'll also see the older git checkout -b feature — identical result. Git split the overloaded old checkout into two clearer commands in 2019: switch (change branches) and restore (undo file edits). Both spellings still work.",
   syntax:[{t:"git switch",k:"cmd"},{t:"-c",k:"flag",note:"“create” — make a new branch before switching to it (without -c, switch only moves to a branch that already exists)"},{t:"<branch>",k:"arg",note:"the name for your new branch — here, feature"}],
   goal:"Create a branch called feature and switch onto it.",
   target:{local:{main:['c0','c1'],feature:['c0','c1']},HEAD:'feature'},
   chk:function(){return S.HEAD!=='main'}},
  {t:"Commit on the branch",cmd:"git add + commit",
   lay:"You edited app.txt. Now do the usual stage-then-commit dance — but watch where it lands: your commit attaches to feature, and main doesn't budge. That's the entire point of branches: a safe sandbox where you can break things without touching the main timeline.",
   tech:"git commit always records onto whatever branch HEAD points at — and right now that's feature. So feature gains a new commit while main stays exactly where it was. In the graph the two lines visibly diverge: main holds still while feature grows by one. Nothing you do here can disturb main.",
   syntax:[{t:"git add",k:"cmd"},{t:".",k:"arg",note:"stage everything in the current folder — here, app.txt"},{t:";",k:"sh",note:"a shell separator (not part of git) — runs the next command after this one; pressing Enter between the two works too"},{t:"git commit",k:"cmd"},{t:"-m",k:"flag",note:"short for “message” — write the commit message right here instead of opening an editor"},{t:"\"<message>\"",k:"arg",note:"your description of the change, in quotes — e.g. “feature work”"}],
   goal:"Stage and commit app.txt. It should land on feature, not main.",
   target:{local:{main:['c0','c1'],feature:['c0','c1','c2']},HEAD:'feature'},
   setup:function(){S.local.feature=S.local.main.slice();S.HEAD='feature';fb='feature';seed('app.txt')},
   chk:function(){return S.HEAD!=='main'&&hl(S.HEAD)>hl('main')}},
  {t:"Hop back to main",
   lay:"git switch main walks you back over to the main branch. Notice your feature commit isn't here — it hasn't vanished, it's just safely tucked away on the other branch, waiting for you. Switching is like changing rooms: the work in the other room is still there when you go back.",
   tech:"Switching repoints HEAD to main and rewrites the files in your working folder to match whatever main points at — so app.txt's commit simply isn't part of this view. Your feature work is untouched on its own branch. Handy shortcut: git switch - (a bare dash) jumps to the branch you were JUST on, like alt-tab for branches. git checkout - does the same.",
   syntax:[{t:"git switch",k:"cmd"},{t:"<branch>",k:"arg",note:"the branch to move onto — here, main. (Use a bare dash, git switch -, to flip back to the branch you were just on.)"}],
   goal:"Switch back to main. Notice your feature commit isn't on this branch.",
   target:{local:{main:['c0','c1'],feature:['c0','c1','c2']},HEAD:'main'},
   setup:function(){S.local.feature=S.local.main.concat(['c2']);S.HEAD='feature';fb='feature';S.prev='main'},
   chk:function(){return S.HEAD==='main'}},
  {t:"Delete the branch",
   lay:"You're done with feature for now, so git branch -D feature throws the branch away. We're using the capital -D here on purpose: the polite lowercase -d would refuse, because feature has commits you never merged anywhere — git won't let you lose work by accident. The capital D is you saying “yes, I really mean it.”",
   tech:"Lowercase -d is the safe delete: it checks the branch is fully merged into main and aborts otherwise. Capital -D forces it regardless. Either way you're only removing the sticky note — the commits themselves linger unreferenced for a while and can still be rescued via the reflog (you'll meet it later). Since feature's commit was never merged, only -D will go through.",
   syntax:[{t:"git branch",k:"cmd"},{t:"-D",k:"flag",note:"force-delete — removes the branch even if it has unmerged commits (the lowercase -d refuses in that case to protect your work)"},{t:"<branch>",k:"arg",note:"the branch to delete — here, feature"}],
   goal:"Delete the feature branch. It isn't merged, so the safe -d will refuse — use the force.",
   target:{local:{main:['c0','c1']},HEAD:'main'},
   setup:function(){S.local.feature=S.local.main.concat(['c2']);S.HEAD='main';fb='feature'},
   chk:function(){return !S.local.feature}}
 ],
 recap:"branch = list · switch -c / checkout -b = create+move · switch - = back to previous · branch -d = safe delete, -D = force delete."},

{sec:"Essentials",title:"Merging",diff:2,show:{branches:true,graph:true},selfContained:true,
 blurb:"Branching is only half the story — eventually good work needs to come home. Merging pulls one branch's commits into another. The one rule to tattoo on your brain: only the branch you're STANDING ON changes.",
 onEnter:function(){S=blank();S.local={main:['c0','c1'],feature:['c0','c1','f1','f2']};fb=null},
 missions:[
  {t:"A clean fast-forward",
   lay:"git merge feature pours the commits from feature into the branch you're currently on. You're standing on main, and main hasn't budged since feature split off — so git doesn't have to do anything clever, it just slides main forward to catch up. People call this a “fast-forward,” and it's the easy, everyday case.",
   tech:"Because main is a direct ancestor of feature, there's nothing to reconcile — git simply moves main's pointer up to the same commit feature points at. No new merge commit is created, and the history stays a single straight line. Note that feature is untouched: only main, the branch HEAD is on, moves.",
   syntax:[{t:"git merge",k:"cmd"},{t:"feature",k:"arg",note:"the branch you want to bring IN — its commits get merged into the branch you're currently standing on (here, main)"}],
   goal:"You're on main, and feature is just ahead of it. Merge feature into main.",
   setup:function(){S.local={main:['c0','c1'],feature:['c0','c1','f1','f2']};S.HEAD='main';fb='feature'},
   target:{local:{main:['c0','c1','f1','f2'],feature:['c0','c1','f1','f2']},HEAD:'main'},
   chk:function(){return S.local.feature.every(function(x){return S.local.main.indexOf(x)>-1})}},
  {t:"A real merge commit",
   lay:"Same command, git merge hotfix, but a different situation: this time BOTH branches grew new commits after they split, so there's no straight line to slide along. Git can't fast-forward, so it stitches the two histories together with a special “merge commit” — the M node — that ties everything back into one timeline.",
   tech:"When the two branches have diverged, git creates a brand-new commit with TWO parents (one from each branch) and points main at it. That merge commit is the permanent record of exactly when the two lines rejoined. Good to know: git merge --no-ff forces this tidy merge commit even when a plain fast-forward would have worked — some teams prefer it so a branch's commits stay visibly grouped.",
   syntax:[{t:"git merge",k:"cmd"},{t:"hotfix",k:"arg",note:"the diverged branch to bring in — because both branches moved, this produces a merge commit (the M node) instead of a fast-forward"},{t:"--no-ff",k:"flag",note:"optional — “no fast-forward”: forces a merge commit even when git could have just slid forward, keeping the branch's history grouped"}],
   goal:"main and hotfix have each gained their own new commit. Merge hotfix into main and watch a merge commit appear.",
   setup:function(){S.local={main:['c0','c1','m3'],hotfix:['c0','c1','h1']};S.HEAD='main';fb='hotfix'},
   target:{local:{main:['c0','c1','m3','h1','M4'],hotfix:['c0','c1','h1']},HEAD:'main'},
   chk:function(){return (S.local.main.indexOf('h1')>-1)&&S.local.main.some(function(x){return x[0]==='M'})}}
 ],
 recap:"merge brings another branch INTO the one you're standing on · fast-forward = main slides forward in a straight line · a merge commit (M) ties two diverged lines together · --no-ff forces a merge commit."},

{sec:"Essentials",title:"Merge conflicts",diff:3,show:{branches:true,graph:true},selfContained:true,
 blurb:"The moment every beginner dreads, defused. A conflict just means two branches edited the SAME line and git refuses to guess which you meant. It's not an error — it's git asking you a polite question.",
 onEnter:function(){S=blank();S.local={main:['c0','c1','mx'],feature:['c0','c1','fx']};S.conflict=false;fb='feature'},
 missions:[
  {t:"Trigger the conflict",
   lay:"git merge feature tries to bring the feature branch's work into the branch you're standing on. Usually it just blends the two and moves on. But here both branches edited the very same line of title.txt, so git stops and shrugs: it genuinely can't tell which version you wanted. That pause is a “merge conflict.”",
   tech:"Git compares the two branches against their common ancestor. Where only one side changed a region, it takes that change automatically. Where BOTH sides changed the same lines, it can't auto-resolve, so it pauses the merge, marks the file as “both modified,” and writes both versions into title.txt surrounded by <<<<<<< / ======= / >>>>>>> markers. The merge is left half-finished until you say how it should end.",
   syntax:[{t:"git merge",k:"cmd"},{t:"<branch>",k:"arg",note:"the branch whose commits you want to pull into the one you're currently on — here, feature"}],
   goal:"You're on main. Both main and feature changed the same line of title.txt. Run the merge and watch it stop on a conflict.",
   setup:function(){S.HEAD='main';fb='feature'},
   chk:function(){return S.conflict===true}},
  {t:"Resolve and stage",cmd:"git add",
   lay:"There's no magic “fix it” button — you settle a conflict yourself, then git add the file to announce it's sorted. You open title.txt, delete the <<<<<<< ======= >>>>>>> markers, keep the lines you actually want, and stage the file. Staging a conflicted file is your way of telling git “I looked, I chose, this one's done.”",
   tech:"Once you've hand-edited title.txt into its final form, git add records that resolved version in the staging area and clears the file's “unmerged” status. If you'd rather not deal with it at all, git merge --abort rewinds everything to exactly how it was before you started the merge — no trace left.",
   syntax:[{t:"git add",k:"cmd"},{t:"<file>",k:"arg",note:"the file you just resolved — here title.txt; or “.” to stage every resolved file at once"}],
   goal:"You've edited title.txt to keep the right line and removed the markers. Stage it to tell git the conflict is resolved.",
   setup:function(){S.conflict=true;S.working.push('title.txt');S.HEAD='main';fb='feature'},
   chk:function(){return S.conflict==='resolved'}},
  {t:"Seal the merge",cmd:"git commit",
   lay:"git commit finishes the job. One last commit bundles your hand-picked resolution into a merge commit, and the two branches are officially joined. Git usually writes the message for you, so most of the time you just confirm it. That's it — you've survived the thing everyone warns you about.",
   tech:"Because a merge was in progress, this commit becomes a merge commit (the M node) with two parents — main and feature — recording exactly where the two lines rejoined. Its content is the resolved file you staged. Once it lands, the conflict state is fully cleared and main now contains feature's work.",
   syntax:[{t:"git commit",k:"cmd"},{t:"-m",k:"flag",note:"attaches the commit message inline instead of opening an editor — though for a merge git pre-fills a sensible message, so you can often leave -m off and just save"},{t:"\"<message>\"",k:"arg",note:"a short description — for example “merge feature”"}],
   goal:"Commit to finish the merge with the message “merge feature”.",
   setup:function(){S.conflict='resolved';S.staging.push('title.txt');S.HEAD='main';fb='feature'},
   target:{local:{main:['c0','c1','mx','fx','M2'],feature:['c0','c1','fx']},HEAD:"main"},
   chk:function(){return S.conflict===false&&S.local.main.indexOf('fx')>-1}}
 ],
 recap:"Conflict = two branches touched the same line. Fix: edit file, remove the <<< === >>> markers, git add, git commit. Bail out anytime with git merge --abort."},

{sec:"Essentials",title:"The undo button",diff:2,show:{branches:true,graph:true},selfContained:true,
 blurb:"Git's superpower is that almost nothing is permanent — IF you know the right undo. There's a different one for each “oops,” so let's learn them by the mess they clean up.",
 onEnter:function(){S=blank();S.local={main:['c0','c1','c2']};fb=null},
 missions:[
  {t:"Unstage a file",
   lay:"git restore --staged pulls a file back out of the box you were about to seal. You staged secrets.txt by accident — this lifts it out of staging and sets it back on your desk, with every edit untouched. It's the “oops, wrong file in the box” undo, not the “delete my work” one.",
   tech:"It copies the file's entry from the last commit back over the staging area, so the file is no longer lined up for the next commit — but your working-folder copy is left exactly as it was. The old spelling git reset HEAD <file> does the identical thing; restore --staged is just the clearer modern wording.",
   syntax:[{t:"git restore",k:"cmd"},{t:"--staged",k:"flag",note:"act on the staging area, not your working files — this is what makes restore unstage rather than discard"},{t:"<file>",k:"arg",note:"the file to pull back out of staging — here it's secrets.txt"}],
   goal:"You staged secrets.txt by mistake. Unstage it so it's no longer packed for the next commit, keeping the edits on your desk.",
   setup:function(){seed('secrets.txt');S.staging.push(S.working.pop())},
   chk:function(){return S.staging.indexOf('secrets.txt')<0&&S.working.indexOf('secrets.txt')>-1}},
  {t:"Throw away an edit",
   lay:"git restore (no flag this time) wipes the changes in a file and snaps it back to how it looked in your last commit. You made a mess of draft.txt and just want the old version back — this is that reset-the-page button. Because there's no recycle bin for unsaved work, this is the one undo worth a deep breath before you press Enter.",
   tech:"It overwrites your working-folder copy of the file with the version stored in the last commit. Any uncommitted edits to that file are gone for good — git never staged or saved them, so there's nothing to recover. The old spelling git checkout -- <file> does the same overwrite.",
   syntax:[{t:"git restore",k:"cmd"},{t:"<file>",k:"arg",note:"the file to reset to its last committed state — here draft.txt. With no --staged flag, restore overwrites your working copy"}],
   goal:"You messed up draft.txt and want it back exactly as the last commit. Discard the change.",
   setup:function(){seed('draft.txt')},
   chk:function(c){return /^git\s+restore\s+draft\.txt|^git\s+checkout\s+--\s+draft\.txt/.test(c.trim())&&S.working.indexOf('draft.txt')<0}},
  {t:"Fix the last commit",
   lay:"git commit --amend lets you redo your most recent commit instead of stacking a new one on top. Perfect for a typo in the message, or a file you forgot to include. Think of it as peeling the label off the last box and writing a fresh one, rather than taping on a whole second box.",
   tech:"It replaces the most recent commit with a new one that has the updated message and whatever is currently staged folded in. Under the hood the original commit is discarded and a brand-new commit (with a new id) takes its place — which is exactly why you should never amend a commit you've already pushed: your teammates still hold the old one. Amend in private, push in public.",
   syntax:[{t:"git commit",k:"cmd"},{t:"--amend",k:"flag",note:"rewrite the last commit instead of making a new one — folds in any staged changes and lets you redo the message"},{t:"-m",k:"flag",note:"short for “message” — supply the corrected message right here instead of opening an editor"},{t:"\"<message>\"",k:"arg",note:"you replace this — the fixed commit message, in quotes"}],
   goal:"Your last commit message had a typo. Amend it (any corrected message) instead of making a new commit.",
   chk:function(c){return /^git\s+commit\s+--amend/.test(c.trim())}},
  {t:"Undo a whole commit (3 flavours)",
   lay:"git reset slides your branch's sticky note backwards, “un-committing” the last commit — and a flag decides what happens to the changes that were in it. With --soft, those changes drop straight back into staging, ready for you to fix them up and commit again. It's the gentle rewind: the commit is undone, but nothing you wrote is lost.",
   tech:"reset moves the current branch pointer back by one commit (HEAD~1 = “one before HEAD”), then sorts out your files according to the flag. --soft leaves staging and working folder alone, so the undone commit's changes sit in staging. --mixed (the default) also clears staging, dropping the changes into your working folder unstaged. --hard resets everything, throwing those changes away entirely — the chainsaw, and the cause of most “oh no” moments. (Lost something to --hard? The “Safe undo & recovery” chapter brings it back with reflog.)",
   syntax:[{t:"git reset",k:"cmd"},{t:"--soft",k:"flag",note:"keep the undone commit's changes in STAGING, ready to re-commit. (--mixed drops them into your working folder unstaged; --hard deletes them — no undo)"},{t:"HEAD~1",k:"arg",note:"how far back to move — HEAD~1 means “one commit before where you are now.” Omit it and reset only touches staging, not the commit history"}],
   goal:"That last commit (c2) was premature. Roll the branch back one commit but keep its changes in staging, so you can redo it.",
   target:{local:{main:['c0','c1']},HEAD:"main"},
   chk:function(){return hl('main')===2&&S.staging.length>0}}
 ],
 recap:"restore --staged = unstage · restore FILE = discard edit · commit --amend = fix last commit (private only) · reset --soft/--mixed/--hard = undo a commit, keeping/unstaging/destroying the changes."},

{sec:"Essentials",title:"Ignoring files",diff:1,show:{},selfContained:true,
 blurb:"Some files should never be committed: passwords, giant build folders, OS clutter like .DS_Store. A file called .gitignore is git's bouncer — names on the list don't get past the velvet rope and into your history.",
 onEnter:function(){S=blank();S.local={main:['c0']};S.ignored=false;fb=null},
 missions:[
  {t:"Spot the junk",
   lay:"git status is your “where are we?” check again, and this time it's pointing out a problem: your folder holds app.txt (real work) and debug.log (throwaway clutter your program coughed up). Git tracks everything by default, so it's eyeing them both — including the one nobody else should ever see.",
   tech:"git status lists every untracked file in your working directory, including junk like debug.log. Git doesn't know the difference between “real” and “junk” — to it, an untracked file is an untracked file. Until you tell it otherwise, anything in the folder is a candidate for the next commit.",
   syntax:[{t:"git status",k:"cmd",note:"takes no arguments — it just reports what's in your folder and staging area, and never changes anything"}],
   goal:"Run a status check to see both app.txt and debug.log waiting in your folder.",
   setup:function(){seed('app.txt');seed('debug.log')},
   chk:function(c){return /^git\s+status/.test(c.trim())}},
  {t:"Add it to .gitignore",
   lay:"A .gitignore file is git's do-not-track list. Add debug.log to it (the button below does the writing for you) and git stops pestering you about that file forever — it won't show up in status, and git add . will quietly skip it.",
   tech:"A .gitignore is just a plain text file of patterns, one per line: a literal name like debug.log, a wildcard like *.log to catch all log files, or node_modules/ to ignore a whole folder. Git checks every untracked file against this list and pretends the matches don't exist. Crucially, you DO commit the .gitignore itself, so your whole team shares one bouncer list.",
   syntax:[{t:"click “Add debug.log to .gitignore”",k:"arg",note:"this step has no command to type — in real life you'd open the .gitignore file in your editor and add a line like debug.log (or *.log); the button does that for you here"}],
   goal:"Use the button below to add debug.log to your .gitignore file.",
   action:{label:'<i class="ti ti-eye-off" aria-hidden="true"></i> Add debug.log to .gitignore',run:function(){var i=S.working.indexOf('debug.log');if(i>-1)S.working.splice(i,1);S.ignored=true;line("Added line to .gitignore:  debug.log",'ok');note("git now ignores debug.log. If it were ALREADY committed, you'd also run: git rm --cached debug.log (stop tracking it, but keep the file on disk).");}},
   setup:function(){seed('app.txt');seed('debug.log')},
   chk:function(){return S.ignored===true}},
  {t:"Commit the real work only",cmd:"git add + commit",
   lay:"Now do the full add → commit loop. Because debug.log is on the ignore list, git add . scoops up app.txt and the .gitignore but leaves the junk behind. You commit only what matters, and the throwaway file never touches your history.",
   tech:"git add . stages every untracked or changed file in the current folder — except anything matching .gitignore, which git silently passes over. The commit then seals just those staged files. If a file is ALREADY tracked, adding it to .gitignore won't untrack it; for that you run git rm --cached FILE, which stops tracking it while leaving the file safely on your disk.",
   syntax:[{t:"git add",k:"cmd"},{t:".",k:"arg",note:"stage everything in the current folder — ignored files are skipped automatically"},{t:";",k:"sh",note:"a shell separator (not part of git) — runs the next command after this one; you could also just press Enter between them"},{t:"git commit",k:"cmd"},{t:"-m",k:"flag",note:"short for “message” — write the commit message right here instead of opening an editor"},{t:"\"<message>\"",k:"arg",note:"your message in quotes, e.g. “add app + ignore logs”"}],
   goal:"Stage everything and commit it with the message “add app + ignore logs”. Confirm debug.log stayed out.",
   setup:function(){seed('app.txt');seed('.gitignore');seed('debug.log');S.ignored=true},
   chk:function(){return hl('main')>=2&&S.working.indexOf('debug.log')>-1}}
 ],
 recap:".gitignore lists files/patterns git should never track (secrets, build junk, *.log, node_modules/). Commit the .gitignore itself so the team shares it. Untrack an already-tracked file with git rm --cached FILE."},

{sec:"Essentials",title:"Going online",diff:2,show:{branches:true,remotes:true,graph:true},selfContained:true,
 blurb:"Everything so far lived on your laptop. “origin” is your project's copy on GitHub. push sends commits up; pull brings commits down. This is the moment git stops being a private diary and turns into teamwork.",
 onEnter:function(){S=blank();S.local={main:['c0','c1']};fb=null},
 missions:[
  {t:"See your remotes",
   lay:"git remote -v shows you the other copies of your project that git knows how to reach — the repos living somewhere else, usually on GitHub. It just reads and lists them; it sends nothing and changes nothing, so it's safe to poke at any time.",
   tech:"A “remote” is a saved nickname paired with a URL. git remote on its own prints just the names; the -v (“verbose”) flag also prints each one's fetch and push URL. The nickname “origin” is the conventional name git gives the repo you cloned from — it's a plain label stored in your .git config, not anything magical.",
   syntax:[{t:"git remote",k:"cmd"},{t:"-v",k:"flag",note:"“verbose” — also shows each remote's full URL, not just its name; without it you only see the nicknames"}],
   goal:"List the remote repositories git knows about, with their URLs.",
   setup:function(){S.local={main:['c0','c1']};S.origin={main:['c0','c1']}},
   chk:function(c){return /^git\s+remote/.test(c.trim())}},
  {t:"Push to origin",
   lay:"git push -u origin main uploads your commits to the shared copy on GitHub so your teammates (and future-you on another machine) can see them. The interesting part is the -u: it ties your local main to origin's main once, so that from then on a bare git push just knows where to go.",
   tech:"push uploads the commits origin is missing and moves origin's branch pointer forward to match yours. The -u flag (long form --set-upstream) records origin/main as the “upstream” of your local main in .git config; afterwards git push and git pull need no arguments because git already knows the pairing. You only pass -u origin main the very first time you publish a branch.",
   syntax:[{t:"git push",k:"cmd"},{t:"-u",k:"flag",note:"short for --set-upstream — links your local branch to the remote one so future push/pull need no arguments; only needed the first time"},{t:"origin",k:"arg",note:"which remote to push to — “origin” is your GitHub copy"},{t:"main",k:"arg",note:"which local branch to upload"}],
   goal:"Upload your main branch to origin for the first time, setting up the upstream link.",
   setup:function(){S.local={main:['c0','c1']}},
   chk:function(){return S.origin.main&&S.origin.main.length===S.local.main.length}},
  {t:"Pull a teammate's change",
   lay:"A teammate pushed a commit called T1 up to origin, and now you want it on your laptop. git pull reaches up to origin, grabs the new commits, and stitches them into your branch in one move — your local copy catches up to the team.",
   tech:"git pull is really two commands wearing one coat: git fetch (download new commits, change nothing you can see) followed immediately by an integration step (merge by default). If you'd rather inspect before integrating, run git fetch alone and look around first; pull is just the everyday shortcut that does both.",
   syntax:[{t:"git pull",k:"cmd"},{t:"origin",k:"arg",note:"the remote to pull from — or omit it (and the branch) entirely once -u is set"},{t:"main",k:"arg",note:"the branch to pull — here, main"}],
   goal:"A teammate pushed commit T1 to origin. Bring it down onto your laptop.",
   target:{local:{main:['c0','c1','T1']},HEAD:"main"},
   setup:function(){S.local={main:['c0','c1']};S.origin={main:['c0','c1','T1']}},
   chk:function(){return S.local.main.indexOf('T1')>-1}},
  {t:"Pull, but keep history tidy",
   lay:"This time you AND the remote both have new commits — you made “mine” locally while T2 landed upstream. A plain pull would tie them together with a little merge commit; git pull --rebase instead picks up your local commits and replants them neatly on top of the downloaded ones, keeping history as one straight line.",
   tech:"With --rebase, git fetches the remote commits, then replays your local-only commits on top of them one by one, rewriting them with new ids. The result is a linear history with no merge bubble. Many teams set this as their default for everyday pulls. It's a gentle preview of rebase, which you'll meet properly in a later chapter.",
   syntax:[{t:"git pull",k:"cmd"},{t:"--rebase",k:"flag",note:"replay your local commits on top of the downloaded ones instead of making a merge commit — keeps history a straight line"},{t:"origin",k:"arg",note:"the remote to pull from"},{t:"main",k:"arg",note:"the branch to pull"}],
   goal:"Commit T2 landed upstream while you had a local commit called “mine”. Pull it with rebase to avoid a merge bubble.",
   target:{local:{main:['c0','c1','T1','T2','mine']},HEAD:"main"},
   setup:function(){S.local={main:['c0','c1','T1','mine']};S.origin={main:['c0','c1','T1','T2']}},
   chk:function(){return S.local.main.indexOf('T2')>-1}}
 ],
 recap:"remote -v = list remotes · push -u origin main = upload + link (once) · push/pull = up/down after that · fetch = download only · pull --rebase = tidy straight line instead of a merge bubble."},

{sec:"Essentials",title:"Fork & contribute",diff:3,show:{branches:true,remotes:true,upstream:true,graph:true},selfContained:true,
 blurb:"This is the real open-source contribution flow — how a stranger on the internet gets their code into someone else's project. The trick is two remotes. “upstream” is the ORIGINAL repo (say, Anthropic's); you can only read from it and politely propose changes. “origin” is your own fork; you push there freely. Two remotes, two very different jobs.",
 onEnter:function(){S=blank();S.local={main:['base']};S.origin={main:['base']};S.upstream={main:['base','U1']};fb=null;prDone=false},
 missions:[
  {t:"See both remotes",
   lay:"git remote -v lists the other copies of this project that git knows how to talk to. In a fork workflow there are two of them, and telling them apart is the whole game: origin is your personal fork (you can push here), upstream is the original project (you can only read from here — the maintainers decide what gets in).",
   tech:"A remote is just a saved nickname for a repository URL. git remote -v prints each nickname alongside its fetch and push addresses. “origin” is created automatically when you clone a repo (to contribute, you usually clone your own fork); you add “upstream” by hand (git remote add upstream <url>) so your fork remembers where it came from.",
   syntax:[{t:"git remote",k:"cmd"},{t:"-v",k:"flag",note:"short for “verbose” — without it you get just the names; with it you also see each remote's URL, so you can confirm which is your fork and which is the original"}],
   goal:"List the remotes git knows about — you should see origin (your fork) and upstream (the original project).",
   chk:function(c){return /^git\s+remote/.test(c.trim())}},
  {t:"Branch for your work",
   lay:"git switch -c add-skill creates a fresh branch called add-skill and steps you onto it. The golden rule of contributing: never work on main. One branch = one idea = one pull request keeps your proposal clean, easy to review, and easy to abandon if the maintainers say no thanks.",
   tech:"As before, -c creates the branch from wherever HEAD currently points and moves you onto it. Keeping main untouched matters here for a second reason: a pristine main is what you'll later sync against upstream, so your next branch always starts from the project's current code instead of something stale.",
   syntax:[{t:"git switch",k:"cmd"},{t:"-c",k:"flag",note:"“create” — make a new branch and switch to it in one step (older spelling: git checkout -b)"},{t:"add-skill",k:"arg",note:"the branch name — pick something descriptive for the change you're proposing; here we're calling it add-skill"}],
   goal:"Create a branch called add-skill and switch onto it, so your work stays off main.",
   target:{local:{main:['base'],'add-skill':['base']},HEAD:'add-skill'},
   chk:function(){return S.HEAD!=='main'}},
  {t:"Stage & commit",cmd:"git add + commit",
   lay:"This is the same edit → add → commit loop you already know by heart — nothing new, except now it's landing on your add-skill branch instead of main. You wrote skill.md; stage it, then seal it into history with a message so reviewers can follow your reasoning.",
   tech:"git add copies skill.md from your working folder into the staging area; git commit -m records the staged contents as a new commit on the current branch (add-skill). main doesn't move — only the branch you're standing on gains the commit.",
   syntax:[{t:"git add",k:"cmd"},{t:".",k:"arg",note:"stage everything in the current folder — or name skill.md specifically"},{t:";",k:"sh",note:"a shell separator (not part of git) — runs the next command after this one; pressing Enter between the two commands works too"},{t:"git commit",k:"cmd"},{t:"-m",k:"flag",note:"“message” — write the commit message inline instead of opening an editor"},{t:"\"<message>\"",k:"arg",note:"your message in quotes, e.g. “add skill”"}],
   goal:"Stage skill.md and commit it on the add-skill branch with the message “add skill”.",
   setup:function(){S.local['add-skill']=S.local.main.slice();S.HEAD='add-skill';fb='add-skill';seed('skill.md')},
   target:{local:{main:['base'],'add-skill':['base','s1']},HEAD:'add-skill'},
   chk:function(){return S.HEAD!=='main'&&hl(S.HEAD)>1}},
  {t:"Push to YOUR fork",
   lay:"git push -u origin add-skill uploads your add-skill branch to origin — your fork on GitHub. You push to origin and not upstream for one simple reason: origin is the only repo you're allowed to write to. Try pushing to upstream and you'd be bounced at the door, which is exactly the point.",
   tech:"push sends your local branch's commits to the named remote and branch. The -u flag sets up tracking, linking your local add-skill to origin/add-skill so future bare git push and git pull on this branch just know where to go. Your commits now live on your fork, pushed and ready to be proposed.",
   syntax:[{t:"git push",k:"cmd"},{t:"-u",k:"flag",note:"short for --set-upstream — remembers the link between your local branch and origin/add-skill, so next time a bare git push works"},{t:"origin",k:"arg",note:"the remote to push to — your fork, the one you can write to"},{t:"add-skill",k:"arg",note:"the branch to upload — your local add-skill branch"}],
   goal:"Push your add-skill branch up to origin (your fork), setting it as the upstream tracking branch.",
   setup:function(){S.local['add-skill']=S.local.main.concat(['s1']);S.HEAD='add-skill';fb='add-skill'},
   chk:function(){return fb&&S.origin[fb]&&S.origin[fb].length===S.local[fb].length}},
  {t:"Sync your main with upstream",cmd:"git switch main + git pull upstream main",
   lay:"While you were busy, the original project moved on — it gained a new commit, U1. git pull upstream main grabs the latest from the original repo and merges it into whatever branch you're on, so first you switch to main, THEN pull. This is the step beginners skip, then wonder why their next branch fights with everything.",
   tech:"git switch main moves HEAD back to your pristine main. git pull upstream main is fetch + merge against the upstream remote: it downloads upstream's main and fast-forwards your local main to match (here, picking up U1). Because your main had no commits of its own, it slides cleanly forward with no merge commit.",
   syntax:[{t:"git switch",k:"cmd"},{t:"main",k:"arg",note:"the branch to move onto — you must be on main before pulling into it"},{t:";",k:"sh",note:"a shell separator (not part of git) — runs the pull after the switch"},{t:"git pull",k:"cmd"},{t:"upstream",k:"arg",note:"the remote to pull from — the original project, not your fork"},{t:"main",k:"arg",note:"the branch on upstream to pull — its main"}],
   goal:"Switch to main, then pull from upstream main to bring the new commit U1 into your local main.",
   setup:function(){S.local['add-skill']=S.local.main.concat(['s1']);S.origin['add-skill']=S.local['add-skill'].slice();S.HEAD='add-skill';fb='add-skill'},
   target:{local:{main:['base','U1'],'add-skill':['base','s1']},HEAD:'main'},
   chk:function(){return S.local.main.indexOf('U1')>-1}},
  {t:"Open the pull request",
   lay:"A pull request isn't a git command at all — it's you knocking on the maintainers' door and saying “here's my add-skill branch, want it?” They read it, comment, maybe ask for tweaks, then merge it (or don't). It's a conversation, not a command, and it's how virtually all collaborative code — including code that lands in Anthropic's repos — actually gets in.",
   tech:"Under the hood there's no git verb for this; the pull request is a feature of the hosting platform (GitHub, GitLab, etc.). It compares the branch you pushed to your fork (origin/add-skill) against the upstream project's main, shows the diff, and gives maintainers a button to merge. Your commits are already pushed — the PR just points at them.",
   syntax:[{t:"(no command)",k:"arg",note:"there's no git command for this — you open a pull request on the website, or with the button below"}],
   goal:"Propose your add-skill branch to the original project by opening a pull request — use the button below.",
   setup:function(){S.local['add-skill']=S.local.main.concat(['s1']);S.origin['add-skill']=S.local['add-skill'].slice();S.HEAD='main';fb='add-skill'},
   action:{label:'<i class="ti ti-git-pull-request" aria-hidden="true"></i> Open pull request',run:function(){if(!fb||!S.origin[fb]){note("push your branch to origin first.");return}prDone=true;line("Opened PR: you:"+fb+" → anthropics/main",'ok');}},
   chk:function(){return prDone}}
 ],
 recap:"origin = your fork (you push here) · upstream = the original (you pull here, propose via PR) · the flow: branch → commit → push to origin → open PR · and sync your main from upstream often so you never drift into the past."},

// ---------- ADVANCED ----------
{sec:"Advanced",title:"Stash",diff:3,show:{branches:true,graph:true},selfContained:true,
 blurb:"The “oh no, the boss needs a fix RIGHT NOW” button. Stash shelves your half-done work so your desk is clean, lets you deal with the emergency, then hands your work back exactly as it was.",
 onEnter:function(){S=blank();S.local={main:['c0','c1']};fb=null},
 missions:[
  {t:"Shelve your mess",
   lay:"git stash is the “sweep my desk clear, but keep everything” button. You're halfway through editing app.txt when an emergency lands — too messy to commit, too valuable to throw away. Stash scoops all your uncommitted work into a hidden drawer and hands you a spotless working folder, ready to deal with the fire.",
   tech:"git stash takes everything in your working directory and staging area, records it as a stash entry (git stores it as a couple of temporary commits behind the scenes), then resets those files back to the last commit — so nothing is lost and nothing is committed. By default it only grabs tracked files; brand-new untracked files stay put unless you add -u.",
   syntax:[{t:"git stash",k:"cmd",note:"with no arguments it shelves all tracked changes (staged + unstaged) and clears your desk"},{t:"-u",k:"flag",note:"short for --include-untracked — also stashes brand-new files git isn't tracking yet, which a plain git stash leaves behind"}],
   goal:"You're mid-edit on app.txt and not ready to commit when an emergency hits. Shelve your changes so your working folder is clean.",
   setup:function(){seed('app.txt')},chk:function(){return S.stash.length>0&&S.working.length===0}},
  {t:"Check the drawer",
   lay:"git stash list is the peek inside the drawer. You can stash more than once, so it's easy to forget what you've parked. This command lists every shelved bundle, newest first, and never touches anything — it's purely a “what's in here?” look.",
   tech:"git stash list prints the stash stack. Each entry gets a reference like stash@{0} for the most recent, stash@{1} for the one before it, and so on. It's a true stack: new stashes push onto the front and bump the numbers down. Nothing is changed — it only reads the list.",
   syntax:[{t:"git stash list",k:"cmd",note:"takes no arguments — just prints every stash entry as stash@{0}, stash@{1}, … newest first"}],
   goal:"List everything currently sitting in your stash.",
   setup:function(){S.stash=[{files:['app.txt']}]},chk:function(c){return /^git\s+stash\s+list/.test(c.trim())}},
  {t:"Get your work back",
   lay:"git stash pop is the “okay, crisis over, give me my work back” button. It takes the most recent bundle out of the drawer and drops those edits right back onto your desk, exactly where you left them — then throws away the now-empty wrapper. If you'd rather keep a copy in the drawer just in case, use git stash apply instead, which restores your work but leaves the entry behind.",
   tech:"git stash pop reapplies the changes from the top stash entry (stash@{0}) into your working directory, then deletes that entry from the stack. git stash apply does the same reapply but keeps the entry, so you can restore it again later (clean it up afterwards with git stash drop). If your current files have moved on, reapplying can itself produce a merge conflict to resolve.",
   syntax:[{t:"git stash pop",k:"cmd",note:"restores your most recent stash and removes it from the drawer — use git stash apply instead if you want to keep a copy parked"}],
   goal:"The emergency is handled. Bring your shelved app.txt edits back onto your desk.",
   setup:function(){S.stash=[{files:['app.txt']}]},chk:function(){return S.stash.length===0&&S.working.length>0}}
 ],
 recap:"stash = park uncommitted work, clean desk · stash list = see the drawer · pop = bring back + remove · apply = bring back + keep · -u also stashes untracked files."},

{sec:"Advanced",title:"Rebase & squash",diff:4,show:{branches:true,graph:true},selfContained:true,
 blurb:"Rebase rewrites history to make it tidy. Instead of merging (which records the messy truth, merge bubble and all), rebase REPLANTS your commits onto a newer base — as if you'd started from there all along. It's powerful, and it's the one tool that comes with a real safety rule.",
 onEnter:function(){S=blank();S.local={main:['c0','c1','c2','c3'],feature:['c0','c1','f1','f2']};S.HEAD='feature';fb='feature'},
 missions:[
  {t:"Replant your branch",
   lay:"git rebase picks up your branch's commits and sets them back down on top of a newer starting point. You branched off main a while ago, and main has marched on since (it grew c2 and c3). Rebase is you saying \"pretend I started from main as it is right now\" — your work gets lifted off the old spot and replanted on the fresh one, in one clean straight line, no merge bubble in sight.",
   tech:"git rebase main finds the commits that are unique to feature, rewinds feature back to the tip of main, then re-applies your commits one by one on top. Because each replayed commit now has a different parent, git gives it a brand-new hash — it is genuinely a new commit, not the same one moved. That's the source of the golden rule: never rebase commits you've already pushed and shared, because you'd be handing everyone else a history that no longer matches the one they're standing on.",
   syntax:[{t:"git rebase",k:"cmd"},{t:"<base>",k:"arg",note:"the branch (or commit) to replant onto — here it's main, the branch whose newest commit you want to sit on top of"}],
   goal:"You're on feature. main has moved ahead to c2 and c3 since you branched. Rebase feature onto main so your commits sit on top of the latest main.",
   target:{local:{main:['c0','c1','c2','c3'],feature:['c0','c1','c2','c3','f1','f2']},HEAD:"feature"},
   chk:function(){return S.local.feature.indexOf('c3')>-1&&S.local.feature.indexOf('f2')>-1}},
  {t:"Squash messy commits into one",
   lay:"git rebase -i opens an interactive to-do list of your recent commits, where you can reorder them, rename them, or \"squash\" several into one. Your branch is littered with the honest mess of real work — an \"oops\", a \"fix typo\", a \"wip2\" — and nobody reviewing your code needs that diary. Squashing melts those scrappy commits together into a single tidy one, so your branch tells one clean story instead of a blow-by-blow account of your afternoon.",
   tech:"The -i (interactive) flag drops you into an editor listing the chosen commits with a keyword beside each — pick, reword, edit, squash, fixup, drop. Marking commits as squash folds their changes into the one above, and git replays the whole sequence to build new commits with new hashes from the rewritten plan. HEAD~3 means \"the last three commits, counting back from where I am.\" Same golden rule as plain rebase: only do this to commits you haven't shared yet.",
   syntax:[{t:"git rebase",k:"cmd"},{t:"-i",k:"flag",note:"interactive — opens the editable to-do list where you mark commits to pick, reword, or squash instead of replaying them silently"},{t:"HEAD~3",k:"arg",note:"how far back to go — HEAD~3 means the last three commits from your current position; adjust the number to cover the commits you want to tidy"}],
   goal:"Your branch has WIP commits like \"oops\" and \"fix typo\". Open an interactive rebase over the last three commits and squash them into a single clean commit.",
   cmd:"git rebase -i",
   setup:function(){S.local={main:['c0','c1'],feature:['c0','c1','oops','fixtypo','wip2']};S.HEAD='feature';fb='feature'},
   target:{local:{main:['c0','c1'],feature:['c0','c1','squashed']},HEAD:'feature'},
   chk:function(c){return /^git\s+rebase\s+-i/.test(c.trim())}}
 ],
 recap:"rebase <base> = replant your commits onto a newer base (one clean straight line, no merge bubble) · rebase -i = reorder / reword / squash recent commits into a tidy story · GOLDEN RULE: never rebase commits you've already pushed and shared."},

{sec:"Advanced",title:"Cherry-pick",diff:4,show:{branches:true,graph:true},selfContained:true,
 blurb:"Sometimes you don't want a whole branch — you want ONE commit out of it. Cherry-pick is copy-paste for a single commit: pluck the one you need and leave the rest behind.",
 onEnter:function(){S=blank();S.local={main:['c0','c1'],feature:['c0','c1','fixA','fancyB']};fb=null},
 missions:[
  {t:"Grab one commit",
   lay:"git cherry-pick reaches over to another branch, grabs the changes from one specific commit, and drops a copy onto the branch you're standing on right now. Here feature has a finished bug fix (fixA) you need on main today, but the rest of feature (the half-built fancyB) isn't ready — so instead of merging the whole branch, you just pluck the one commit you want, like taking a single cherry off the tree and leaving the others to ripen.",
   tech:"Cherry-pick re-applies the diff introduced by the named commit as a BRAND-NEW commit on your current branch — same changes, but a new identity (a new hash and a new parent), not the original commit moved over. The source branch is left completely untouched. And just like a merge, if that commit's changes overlap lines you've edited elsewhere, you'll get a conflict to resolve the usual way: edit the file, remove the markers, git add, then git cherry-pick --continue.",
   syntax:[{t:"git cherry-pick",k:"cmd"},{t:"<commit>",k:"arg",note:"the commit you want to copy — its hash or id (here, fixA). You can list several to copy a run of commits, or use A..B for a range."}],
   goal:"You're on main. Copy just feature's fixA commit onto main, leaving fancyB behind.",
   setup:function(){S.local={main:['c0','c1'],feature:['c0','c1','fixA','fancyB']};S.HEAD='main';fb=null},
   target:{local:{main:['c0','c1','fixA'],feature:['c0','c1','fixA','fancyB']},HEAD:"main"},
   chk:function(){return S.HEAD==='main'&&S.local.main.indexOf('fixA')>-1&&S.local.main.indexOf('fancyB')<0}}
 ],
 recap:"cherry-pick COMMIT = copy a single commit's changes onto your current branch as a new commit. Perfect for plucking one fix out of an unfinished branch · conflicts resolve just like a merge (edit, git add, cherry-pick --continue)."},

{sec:"Advanced",title:"Force push without crying",diff:4,show:{branches:true,remotes:true,graph:true},selfContained:true,
 blurb:"After you rebase or amend, your local history no longer matches what's on the remote — and git will refuse a normal push. Forcing is how you overwrite the remote. It's a loaded gun; here's how to hold it safely.",
 onEnter:function(){S=blank();S.local={main:['c0','c1','c2r']};S.origin={main:['c0','c1','c2']};fb=null},
 missions:[
  {t:"Watch a normal push get rejected",
   lay:"git push is how you send your local commits up to the shared copy on GitHub. But you rebased main, so your version of history and the remote's version now tell different stories. When you try a plain push, git slams the door — and that's it doing its job, not being difficult.",
   tech:"Git rejects the push with “! [rejected] non-fast-forward.” A normal push only works when your branch is a clean continuation of the remote's — your commits sitting neatly on top of theirs. Here they've genuinely diverged: the remote has commit c2 and your local branch replaced it with c2r. Pushing would have to discard one side, so git refuses and makes you decide on purpose.",
   syntax:[{t:"git push",k:"cmd",note:"with no arguments it sends your current branch to the remote it's linked to — try it and read the rejection"}],
   goal:"Try a plain push and read why git rejects it.",
   setup:function(){S.local={main:['c0','c1','c2r']};S.origin={main:['c0','c1','c2']};S.HEAD='main';fb=null},
   chk:function(c){return /^git\s+push\s*$|^git\s+push\s+origin\s+main\s*$/.test(c.trim())}},
  {t:"The reckless way (so you know the danger)",
   lay:"git push --force is you telling git “stop arguing — make the remote look exactly like mine.” It absolutely works. The catch: if a teammate had pushed commits you hadn't downloaded yet, --force flattens them with zero warning, no “are you sure?”, nothing. This is the command behind most “who deleted my work?!” mysteries. It has its place on a private branch only you touch, but treat it like a chainsaw.",
   tech:"With --force git skips its safety check entirely and overwrites the remote branch so it matches your local one, commit for commit. Any commits that existed only on the remote become unreachable. The short form is -f. There's no negotiation and no record of what was there before — which is exactly why the safer cousin in the next step exists.",
   syntax:[{t:"git push",k:"cmd"},{t:"--force",k:"flag",note:"overwrite the remote branch so it matches yours, no questions asked — its short form is -f"}],
   goal:"Force the push the blunt way, and notice the warning about what it can erase.",
   setup:function(){S.local={main:['c0','c1','c2r']};S.origin={main:['c0','c1','c2']};S.HEAD='main';fb=null},
   chk:function(c){return /^git\s+push\s+(--force|-f)\b/.test(c.trim())&&!/lease/.test(c)}},
  {t:"The safe way (use this one)",
   lay:"git push --force-with-lease is the same overwrite, but with a seatbelt. It checks first: does the remote still look the way it did last time I fetched? If yes, it pushes. If a teammate snuck a commit in since then, it stops cold and warns you instead of bulldozing their work. Make this your reflex — if you ever have to force, force-with-lease.",
   tech:"Before overwriting, --force-with-lease compares the remote branch against the version you last saw (your remote-tracking ref). If they still match, the force goes through. If the remote has moved — meaning someone pushed in the meantime — it aborts and tells you, so you can fetch their work first. Same power as --force, but it refuses to cause friendly fire.",
   syntax:[{t:"git push",k:"cmd"},{t:"--force-with-lease",k:"flag",note:"force only if the remote still matches what you last fetched — otherwise it aborts so you don't clobber a teammate"}],
   goal:"Force-push the diverged main again — this time with the seatbelt on.",
   setup:function(){S.local={main:['c0','c1','c2r']};S.origin={main:['c0','c1','c2']};S.HEAD='main';fb=null},
   chk:function(c){return /force-with-lease/.test(c)}}
 ],
 recap:"After rebase/amend the remote diverges → normal push is rejected. --force / -f overwrites blindly (can erase teammates' work). --force-with-lease overwrites ONLY if the remote hasn't changed since you fetched — always prefer it."},

{sec:"Advanced",title:"Safe undo & recovery",diff:4,show:{branches:true,graph:true},selfContained:true,
 blurb:"Two lifesavers. revert undoes a commit WITHOUT rewriting history, so it's safe even on branches other people share. reflog is git's surveillance tape — it quietly remembers everywhere you've been, so commits you think you've lost usually aren't lost at all.",
 onEnter:function(){S=blank();S.local={main:['c0','c1','bad']};fb=null},
 missions:[
  {t:"Undo a shared commit the safe way",
   lay:"git revert is the gentle, no-regrets undo. Commit “bad” broke production and — worse — you already pushed it, so other people have it too. Instead of pretending it never happened, revert adds a brand-new commit that does the exact opposite of the bad one, quietly cancelling its changes while leaving the original sitting in history for all to see. It's the difference between deleting an awkward email and sending a polite “please ignore my last message” follow-up.",
   tech:"git revert <commit> computes the inverse of the changes that commit introduced and records them as a NEW commit on top of your branch. The bad commit stays exactly where it was; history only grows, never shrinks. That's why it's safe to use on shared branches — nobody's existing commits move or disappear, so no one has to re-sync. Contrast this with git reset, which rewrites history by removing commits: fantastic in a private branch, dangerous once others have pulled. Rule of thumb: reset for unshared mistakes, revert for shared ones.",
   syntax:[{t:"git revert",k:"cmd"},{t:"<commit>",k:"arg",note:"the commit you want to cancel out — here it's bad. git creates a fresh commit undoing its changes (you can also pass a range to revert several)"}],
   goal:"Commit “bad” is already pushed and broke production. Reverse its effect by reverting the commit named bad.",
   target:{local:{main:['c0','c1','bad','revert-bad']},HEAD:"main"},
   chk:function(){return S.local.main.some(function(x){return x.indexOf('revert')>-1})}},
  {t:"Recover a commit you “lost”",cmd:"git reflog",
   lay:"git reflog is git's private CCTV footage — and right now you need it. Earlier you ran git reset --hard and watched a perfectly good commit vanish into thin air. Panic not: git was filming the whole time. The reflog is a running log of everywhere HEAD has stood, so that “destroyed” commit still has an address. This is the command that turns a stomach-dropping git disaster into a shrug.",
   tech:"git reflog prints the history of where HEAD has pointed — every commit, switch, reset, merge and rebase leaves an entry, even moves that no longer appear in the normal branch history. So a commit “erased” by git reset --hard isn't truly gone; it's just unreferenced, and its id is still listed in the reflog. Read the id off the list, then git reset --hard <id> (or git checkout <id>) teleports you straight back to it. This is why experienced developers stay calm when things go sideways: the reflog almost always still has a copy.",
   syntax:[{t:"git reflog",k:"cmd",note:"takes no arguments — it lists everywhere HEAD has been (HEAD@{0} is now, HEAD@{1} is one move ago, and so on). Spot the lost commit's id, then git reset --hard <id> to jump back to it"}],
   goal:"You ran git reset --hard earlier and a good commit disappeared. Show git's movement log so you can find that commit again.",
   setup:function(){S.local={main:['c0','c1']};S.reflog=['reset: moving HEAD to c1 (--hard)','good: the commit you still need','c1: commit','c0: commit']},
   chk:function(c){return /^git\s+reflog/.test(c.trim())}}
 ],
 recap:"revert = safe undo (a new commit that cancels an old one) — use it on shared history · reset = rewrite history — private branches only · reflog = the time machine that finds commits you thought you'd destroyed."},

{sec:"Advanced",title:"Tags & releases",diff:2,show:{branches:true,remotes:true,graph:true},selfContained:true,
 blurb:"Branches move; tags don't. A tag is a permanent bookmark on one specific commit — “this exact code is version 1.0.” That's how releases are marked, so people can always find the precise snapshot you shipped.",
 onEnter:function(){S=blank();S.local={main:['c0','c1','c2']};S.origin={main:['c0','c1','c2']};fb=null},
 missions:[
  {t:"Bookmark this commit",
   lay:"git tag pins a permanent label on the commit you're standing on. Unlike a branch, a tag never wanders off as you keep committing — once you call this one v1.0, it points at this exact snapshot forever. Think of it as a sticky note you can never accidentally peel off.",
   tech:"This bare form creates a “lightweight” tag: just a name stored in the repo that points straight at the current commit's id. There's no extra data attached — no author, no date, no message — it's the leanest possible reference, perfect for a quick personal marker.",
   syntax:[{t:"git tag",k:"cmd"},{t:"<name>",k:"arg",note:"the tag name you're pinning to the current commit — version tags are conventionally written like v1.0, v2.3.1, etc."}],
   goal:"This commit is your first release. Tag it v1.0.",
   chk:function(){return !!S.tags['v1.0']}},
  {t:"Make a proper annotated tag",
   lay:"git tag -a makes a richer, “official” tag that carries a little note with it — who made it and a message describing the release. Lightweight tags are fine for scribbling a marker for yourself; annotated tags are what you reach for when a release is real and other people will rely on it.",
   tech:"With -a the tag becomes a full object stored in the repo (not just a name pointing at a commit): it records the tagger, a timestamp, and the message you pass with -m. Because it's a real object it can also be cryptographically signed, which is why teams use annotated tags for anything they publish.",
   syntax:[{t:"git tag",k:"cmd"},{t:"-a",k:"flag",note:"“annotated” — store the tagger, date and a message instead of just a bare name"},{t:"<name>",k:"arg",note:"the tag name, e.g. v1.1"},{t:"-m",k:"flag",note:"short for “message” — write the tag's description right here instead of opening an editor"},{t:"\"<message>\"",k:"arg",note:"a short description of this release, in quotes — e.g. “first stable release”"}],
   goal:"Real releases use an annotated tag, which stores a message and author. Tag this commit v1.1 with the message “first stable release”.",
   setup:function(){S.local={main:['c0','c1','c2']};S.origin={main:['c0','c1','c2']};S.tags={'v1.0':'c2'};fb=null},
   chk:function(){return !!S.tags['v1.1']}},
  {t:"Push your tags",cmd:"git push origin <tag>",
   lay:"Here's the surprise that catches everyone: a normal git push does NOT send your tags. Your shiny new release tag sits on your machine, invisible to the world, until you push it on purpose. git push origin v1.1 sends that one tag up to the remote so everyone else can see the version you marked.",
   tech:"Tags aren't part of any branch, so a regular push (which only updates branch refs) skips them entirely. You push a specific tag by naming it — git push origin v1.1 — or send every local tag at once with git push --tags. Until then the tag exists only in your local repo.",
   syntax:[{t:"git push",k:"cmd"},{t:"origin",k:"arg",note:"the remote to send to — “origin” is the default name git gives the place you cloned from"},{t:"<tag>",k:"arg",note:"the tag to upload, e.g. v1.1 — or replace “origin <tag>” with the flag --tags to push every tag you have at once"}],
   goal:"Tags don't upload with a normal push. Send your v1.1 tag up to origin (or push them all with --tags).",
   setup:function(){S.local={main:['c0','c1','c2']};S.origin={main:['c0','c1','c2']};S.tags={'v1.0':'c2','v1.1':'c2'};fb=null},
   chk:function(c){return /^git\s+push\s+(origin\s+(v|--tags)|--tags)/.test(c.trim())}}
 ],
 recap:"tag NAME = permanent bookmark on a commit · tag -a NAME -m = annotated tag (message + author, for real releases) · push origin TAG / push --tags = tags don't upload on their own, you send them explicitly."}
];
